- name: Playbook to Install Nexus
  hosts: Nexus
  become: true
  roles:
    - Nexus




- name: Playbook to Install SonarQube
  hosts: SonarQube
  become: true
  roles:
    - Postgres
    - SonarQube